version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto21
  build:
    commands:
      - echo Build completed on `date`
      - mvn clean package -DskipTests

artifacts:
  files:
    - target/*.jar
  discard-paths: yes
